# Generated by Django 5.0.4 on 2024-06-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_jwt_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="jwt_token",
            new_name="jwt_access_token",
        ),
        migrations.AddField(
            model_name="profile",
            name="jwt_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
