# Generated by Django 5.0.4 on 2024-06-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_rename_jwt_token_profile_jwt_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="jwt_access_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="jwt_refresh_token",
        ),
    ]
