databases:
  - name: todoappdb
    plan: free
    databaseName: todoapp
    user: todoapp

services:
  - type: web
    plan: free
    name: todoapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todoapp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todoappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4