name: CI Workflow

on:
  push:
    branches:
      - '**'  # Ejecuta en cualquier rama

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
          python -m pip install pycodestyle

      - name: Run Black
        run: |
          black . --check

      - name: Run pycodestyle
        run: |
          pycodestyle .
